import numpy as np
import pandas as pd

multiClassLabels = [
    'pct',
    'addrpct',
    'trhsloc',
    'typeofid',
    'officrid',
    'offverb',
    'offshld',
    'sex',
    'race',
    'haircolr',
    'eyecolor',
    'build',
    'detailcm',
    'city',
    'sector'
]
binaryLabels = [
    'inout',
    'explnstp',
    'othpers',
    'arstmade',
    'sumissue',
    'offunif',
    'frisked',
    'searched',
    'contrabn',
    'adtlrept',
    'pistol',
    'riflshot',
    'asltweap',
    'knifcuti',
    'machgun',
    'othrweap',
    'pf_hands',
    'pf_wall',
    'pf_grnd',
    'pf_drwep',
    'pf_ptwep',
    'pf_baton',
    'pf_hcuff',
    'pf_pepsp',
    'pf_other',
    'radio',
    'ac_rept',
    'ac_inves',
    'rf_vcrim',
    'rf_othsw',
    'ac_proxm',
    'rf_attir',
    'cs_objcs',
    'cs_descr',
    'cs_casng',
    'cs_lkout',
    'rf_vcact',
    'cs_cloth',
    'cs_drgtr',
    'ac_evasv',
    'ac_assoc',
    'cs_furtv',
    'rf_rfcmp',
    'ac_cgdir',
    'rf_verbl',
    'cs_vcrim',
    'cs_bulge',
    'cs_other',
    'ac_incid',
    'ac_time',
    'rf_knowl',
    'ac_stsnd',
    'ac_other',
    'sb_hdobj',
    'sb_outln',
    'sb_admis',
    'sb_other',
    'rf_furt',
    'rf_bulg',
    'recstat'
]
removeLabels = [
    'addrnum', 'sumoffen', 'crimsusp', 'arstoffn', 'addrtyp', 'aptnum', 'beat', 'post', 'crossst', 'arstoffn', 'premname', 'stinter', 'stname', 'xcoord', 'ycoord', 'comppct', 'compyear', 'dettypcm', 'state', 'dob', 'premtype', 'rescode', 'zip', 'ser_num', 'linecm', 'othfeatr', 'year', 'weight', 'ht_feet', 'ht_inch', 'datestop', 'timestop'
]
numericLabels = ['age', 'repcmd', 'revcmd', 'perstop', 'perobs']
multiClassHash = {
    'addrpct': {
        '1': '001',
        '5': '005',
        '6': '006',
        '7': '007',
        '9': '009',
        '10': '010',
        '13': '013',
        '14': '014',
        '17': '017',
        '18': '018',
        '19': '019',
        '20': '020',
        '22': '022',
        '23': '023',
        '24': '024',
        '25': '025',
        '26': '026',
        '28': '028',
        '30': '030',
        '32': '032',
        '33': '033',
        '34': '034',
        '40': '040',
        '41': '041',
        '42': '042',
        '43': '043',
        '44': '044',
        '45': '045',
        '46': '046',
        '47': '047',
        '48': '048',
        '49': '049',
        '50': '050',
        '52': '052',
        '60': '060',
        '61': '061',
        '62': '062',
        '63': '063',
        '66': '066',
        '67': '067',
        '68': '068',
        '69': '069',
        '70': '070',
        '71': '071',
        '72': '072',
        '73': '073',
        '75': '075',
        '76': '076',
        '77': '077',
        '78': '078',
        '79': '079',
        '81': '081',
        '83': '083',
        '84': '084',
        '88': '088',
        '90': '090',
        '94': '094',
        '100': '100',
        '101': '101',
        '102': '102',
        '103': '103',
        '104': '104',
        '105': '105',
        '106': '106',
        '107': '107',
        '108': '108',
        '109': '109',
        '110': '110',
        '111': '111',
        '112': '112',
        '113': '113',
        '114': '114',
        '115': '115',
        '120': '120',
        '122': '122',
        '123': '123',
    },
    'pct': {
        '1': '001',
        '5': '005',
        '6': '006',
        '7': '007',
        '9': '009',
        '10': '010',
        '13': '013',
        '14': '014',
        '17': '017',
        '18': '018',
        '19': '019',
        '20': '020',
        '22': '022',
        '23': '023',
        '24': '024',
        '25': '025',
        '26': '026',
        '28': '028',
        '30': '030',
        '32': '032',
        '33': '033',
        '34': '034',
        '40': '040',
        '41': '041',
        '42': '042',
        '43': '043',
        '44': '044',
        '45': '045',
        '46': '046',
        '47': '047',
        '48': '048',
        '49': '049',
        '50': '050',
        '52': '052',
        '60': '060',
        '61': '061',
        '62': '062',
        '63': '063',
        '66': '066',
        '67': '067',
        '68': '068',
        '69': '069',
        '70': '070',
        '71': '071',
        '72': '072',
        '73': '073',
        '75': '075',
        '76': '076',
        '77': '077',
        '78': '078',
        '79': '079',
        '81': '081',
        '83': '083',
        '84': '084',
        '88': '088',
        '90': '090',
        '94': '094',
        '100': '100',
        '101': '101',
        '102': '102',
        '103': '103',
        '104': '104',
        '105': '105',
        '106': '106',
        '107': '107',
        '108': '108',
        '109': '109',
        '110': '110',
        '111': '111',
        '112': '112',
        '113': '113',
        '114': '114',
        '115': '115',
        '120': '120',
        '122': '122',
        '123': '123',
    },
    'inout': {
        'I': 'INSIDE',
        'O': 'OUTSIDE',
    },
    'trhsloc': {
        ' ': 'NEITHER',
        'H': 'HOUSING',
        'T': 'TRANSIT',
    },
    'typeofid': {
        'O': 'OTHER',
        'P': 'PHOTO',
        'R': 'REFUSED',
        'V': 'VERBAL',
    },
    'offcrid': {
        ' ': 'NOT LISTED',
        '0': 'NO',
        'I': 'ID',
    },
    'offverb': {
        ' ': 'NOT LISTED',
        '0': 'NO',
        'V': 'VERBAL',
    },
    'offshld': {
        ' ': 'NOT LISTED',
        '0': 'NO',
        'S': 'SHIELD',
    },
    'forceuse': {
        ' ': 'NOT LISTED',
        'DS': 'DEFENSE OF SELF',
        'DO': 'DEFENSE OF OTHER',
        'OR': 'OVERCOME RESISTENCE',
        'OT': 'OTHER',
        'SF': 'SUSPECTED FLIGHT',
        'SW': 'SUSPECTED WEAPON',
    },
    'sex': {
        ' ': 'NOT LISTED',
        'F': 'FEMALE',
        'M': 'MALE',
        'Z': 'UNKNOWN',
    },
    'race': {
        ' ': 'NOT LISTED',
        'A': 'ASIAN/PACIFIC ISLANDER',
        'B': 'BLACK',
        'I': 'AMERICAN INDIAN/ALASKAN NATIVE',
        'P': 'BLACK-HISPANIC',
        'Q': 'WHITE-HISPANIC',
        'W': 'WHITE',
        'X': 'UNKNOWN',
        'Z': 'OTHER',
    },
    'haircolr': {
        ' ': 'NOT LISTED',
        'BA': 'BALD',
        'BK': 'BLACK',
        'BL': 'BLOND',
        'BR': 'BROWN',
        'DY': 'DYED',
        'FR': 'FROSTED',
        'GY': 'GRAY',
        'RD': 'RED',
        'SN': 'SANDY',
        'SP': 'SALT AND PEPPER',
        'WH': 'WHITE',
        'XX': 'UNKNOWN',
        'ZZ': 'OTHER',
    },
    'eyecolor': {
        ' ': 'NOT LISTED',
        'BK': 'BLACK',
        'BL': 'BLUE',
        'BR': 'BROWN',
        'DF': 'TWO DIFFERENT',
        'GR': 'GREEN',
        'GY': 'GRAY',
        'HA': 'HAZEL',
        'MA': 'MAROON',
        'PK': 'PINK',
        'VI': 'VIOLET',
        'XX': 'UNKNOWN',
        'ZZ': 'OTHER',
    },
    'build': {
        ' ': 'NOT LISTED',
        'H': 'HEAVY',
        'M': 'MEDIUM',
        'T': 'THIN',
        'U': 'MUSCULAR',
        'Z': 'UNKNOWN',
    },
    'detailcm': {
        '1': 'ABANDONMENT OF A CHILD',
        '2': 'ABORTION',
        '3': 'ABSCONDING',
        '4': 'ADULTERY',
        '5': 'AGGRAVATED ASSAULT',
        '6': 'AGGRAVATED HARASSMENT',
        '7': 'AGGRAVATED SEXUAL ABUSE',
        '8': 'ARSON',
        '9': 'ASSAULT',
        '10': 'AUTO STRIPPING',
        '11': 'BIGAMY',
        '12': 'BRIBE RECEIVING',
        '13': 'BRIBERY',
        '14': 'BURGLARY',
        '15': 'COERCION',
        '16': 'COMPUTER TAMPERING',
        '17': 'COMPUTER TRESPASS',
        '18': 'COURSE OF SEXUAL CONDUCT',
        '19': 'CPSP',
        '20': 'CPW',
        '21': 'CREATING A HAZARD',
        '22': 'CRIMINAL CONTEMPT',
        '23': 'CRIMINAL MISCHIEF',
        '24': 'CRIMINAL POSSESION OF CONTROLLED SUBSTANCE',
        '25': 'CRIMINAL POSSESSION OF COMPUTER MATERIAL',
        '26': 'CRIMINAL POSSESSION OF FORGED INSTRUMENT',
        '27': 'CRIMINAL POSSESSION OF MARIHUANA',
        '28': 'CRIMINAL SALE OF CONTROLLED SUBSTANCE',
        '29': 'CRIMINAL SALE OF MARIHUANA',
        '30': 'CRIMINAL TAMPERING',
        '31': 'CRIMINAL TRESPASS',
        '32': 'CUSTODIAL INTERFERENCE',
        '33': 'EAVES DROPPING',
        '34': 'ENDANGER THE WELFARE OF A CHILD',
        '35': 'ESCAPE',
        '36': 'FALSIFY BUSINESS RECORDS',
        '37': 'FORGERY',
        '38': 'FORGERY OF A VIN',
        '39': 'FORTUNE TELLING',
        '40': 'FRAUD',
        '41': 'FRAUDULENT ACCOSTING',
        '42': 'FRAUDULENT MAKE ELECTRONIC ACCESS DEVICE',
        '43': 'FRAUDULENT OBTAINING A SIGNATURE',
        '44': 'GAMBLING',
        '45': 'GRAND LARCENY',
        '46': 'GRAND LARCENY AUTO',
        '47': 'HARASSMENT',
        '48': 'HAZING',
        '49': 'HINDERING PROSECUTION',
        '50': 'INCEST',
        '51': 'INSURANCE FRAUD',
        '52': 'ISSUE A FALSE CERTIFICATE',
        '53': 'ISSUE A FALSE FINANCIAL STATEMENT',
        '54': 'ISSUING ABORTION ARTICLES',
        '55': 'JOSTLING',
        '56': 'KIDNAPPING',
        '57': 'KILLING OR INJURING A POILCE ANIMAL',
        '58': 'LOITERING',
        '59': 'MAKING GRAFFITI',
        '60': 'MENACING',
        '61': 'MISAPPLICATION OF PROPERTY',
        '62': 'MURDER',
        '63': 'OBSCENITY',
        '64': 'OBSTRUCTING FIREFIGHTING OPERATIONS',
        '65': 'OBSTRUCTING GOVERNMENTAL ADMINISTRATION',
        '66': 'OFFERING A FALSE INSTRUMENT',
        '67': 'OFFICIAL MISCONDUCT',
        '68': 'PETIT LARCENY',
        '69': 'POSSESSION OF BURGLAR TOOLS',
        '70': 'POSSESSION OF EAVES DROPPING DEVICES',
        '71': 'POSSESSION OF GRAFFITI INSTRUMENTS',
        '72': 'PROHIBITED USE OF WEAPON',
        '73': 'PROMOTING SUICIDE',
        '74': 'PROSTITUTION',
        '75': 'PUBLIC DISPLAY OF OFFENSIVE SEXUAL MATERIAL',
        '76': 'PUBLIC LEWDNESS',
        '77': 'RAPE',
        '78': 'RECKLESS ENDANGERMENT',
        '79': 'RECKLESS ENDANGERMENT PROPERTY',
        '80': 'REFUSING TO AID A PEACE OR POLICE OFFICER',
        '81': 'RENT GOUGING',
        '82': 'RESISTING ARREST',
        '83': 'REWARD OFFICIAL MISCONDUCT',
        '84': 'RIOT',
        '85': 'ROBBERY',
        '86': 'SELF ABORTION',
        '87': 'SEXUAL ABUSE',
        '88': 'SEXUAL MISCONDUCT',
        '89': 'SEXUAL PERFORMANCE BY A CHILD',
        '90': 'SODOMY',
        '91': 'SUBSTITUTION OF CHILDREN',
        '92': 'TAMPERING WITH A PUBLIC RECORD',
        '93': 'TAMPERING WITH CONSUMER PRODUCT',
        '94': 'TAMPERING WITH PRIVATE COMMUNICATIONS',
        '95': 'TERRORISM',
        '96': 'THEFT OF SERVICES',
        '97': 'TRADEMARK COUNTERFEITING',
        '98': 'UNLAWFULLY DEALING WITH FIREWORKS',
        '99': 'UNAUTHORIZED RECORDING',
        '100': 'UNAUTHORIZED USE OF A VEHICLE',
        '101': 'UNAUTHORIZED USE OF COMPUTER',
        '102': 'UNLAWFUL ASSEMBLY',
        '103': 'UNLAWFUL DUPLICATION OF COMPUTER MATERIAL',
        '104': 'UNLAWFUL POSSESSION OF RADIO DEVICES',
        '105': 'UNLAWFUL USE OF CREDIT CARD, DEBIT CARD',
        '106': 'UNLAWFUL USE OF SECRET SCIENTIFIC MATERIAL',
        '107': 'UNLAWFUL WEARING A BODY VEST',
        '108': 'UNLAWFULL IMPRISONMENT',
        '109': 'UNLAWFULLY DEALING WITH A CHILD',
        '110': 'UNLAWFULLY USE SLUGS',
        '111': 'VEHICULAR ASSAULT',
        '112': 'OTHER',
        '113': 'FORCIBLE TOUCHING',
    }
}
# Funcion que refactoriza el dataframe de la base de datos


def refactorDataframe(df):
    refactoredDf = df.drop(columns=removeLabels)
    # Se inicializan las series para los atributos a agregar
    imcSerie = pd.Series()
    daySerie = pd.Series()
    monthSerie = pd.Series()
    daytimeSerie = pd.Series()
    # Se itera sobre las filas del df original
    for i, row in df.iterrows():
        # Se agrega el imc en kg/m2 (considerando weight en lb y height en ft)
        imcSerie.at[i] = (row['weight']*.453) / \
            ((row['ht_feet']*12*.0254) + (row['ht_inch']*.0254))**2
        # Se parsea la fecha y hora del parametro en un string ISO
        strdate = str(row['datestop'])
        year = strdate[-1:-4]
        print(year)
